### ISSUE TITLE
Alternative mathoid server for --texvcinfoUrl because api.formulasearchengine.com is really slow

### ISSUE THREAD

**Issue by leokraemer** [TU-Berlin/mathosphere#102]
Are there alternative servers for the --texvcinfoUrl parameter?

The default http://api.formulasearchengine.com/v1/media/math/check/tex is really slow for me and I can not setup a local [mathoid ](https://www.mediawiki.org/wiki/Mathoid) instance.

**Comment by physikerwelt** [comment]
@leokraemer please describe why you can not set up a local mathoid instance.
There is a guide at

https://github.com/wikimedia/mathoid

which points to some OS dependent setup instructions

https://www.npmjs.com/package/librsvg#installation

For alternative locations you might want to refere to 
wikipedia.org/api/

**Comment by physikerwelt** [comment]
but in your own interest you should try really hard to set up mathoid locally

**Comment by leokraemer** [comment]
I finally succeeded to install mathoid by following the instructions, the most crucial step was to downgrade from the latest node LTS 4.6.0 to node 4.2.3.
Also I had to run `npm install` in the new `\node_modules\mathoid\` folder to install missing packages and rename `config.dev.yaml` to `config.yaml` then I could start the server by running `node server.js`

This really makes the extraction fast, it went from over 1 hour (even with wikipedia.org ad host) to 55 seconds!

Side note: `npm test` fails on the jshint tests, but this does not seem to have an impact on the server.

**Comment by physikerwelt** [comment]
I keep this bug open to investigate potential issues with mathoid together with @d00rman

**Comment by physikerwelt** [comment]
ok I just tested with node 4.4.4 ... no issues

**Comment by physikerwelt** [comment]
v4.6.0 works for me too.
