### ISSUE TITLE
Reproduce definition extraction results

### ISSUE THREAD

**Issue by leokraemer** [TU-Berlin/mathosphere#103]
When trying to reproduce 88 true positives and 337 false negatives for the description extraction I kind of hit a wall. 
With alpha = beta = 1, gamma =0.1 and threshold = 0.6 as in the paper I recieve
fn:	140 fp:	835	 tp:	89	 prec	: 9,63 	recall: 38,86	f1: 15,44
for the strict matching.
After playing with the parameter threshold and not getting better results I realized that the total number of Identifiers for me is (tp + fn) for me is 229. When I looked at the goldstandard I was able to extract 359 definitions, which is less than the (88 + 337=) 425 definitions extracted in the paper. I am really confused right now. Also I found 217 Wikidatalinks, compared to 174 the paper mentions. How does that all make sense? To me it seems as if I'm working on the wrong goldstandard.

**Comment by physikerwelt** [comment]
I'll look into this. But first. I noticed that there is one difference in the identifier recoginition. @leokraemer did you trace down which identifier that is?

**Comment by leokraemer** [comment]
I cannot trace that down, because I don't know which ones it is supposed to find. The paper only states the numbers, not what was found.

**Comment by physikerwelt** [comment]
@leokraemer I tried to run
ran com.formulasearchengine.mathosphere.mlp.cli.CliMainTest#testEval without the _sample suffix. I get the impression that this works fine
com.formulasearchengine.mathosphere.mlp.cli.CliMainTest#testEval and the results look quite ok. Maybe you can give some more details about which program you are running and which results you get on your secreen?

**Comment by leokraemer** [comment]
Yes, I do basically the same. At first I analysed the system.err output but now I switched to try to compute the fp, fn and tp on the fly the same way that is done for the Identifiers. Code can be seen at https://github.com/leokraemer/mathosphere/ and the results do not match. I'll compare with https://github.com/TU-Berlin/mathematicalnamespacediscovery/tree/master/paper/eval/q***.csv to figure out where the problem is. 
Also: I noticed that the combined 377 false negatives and 88 true positives stated in the paper add up to a total of 425 definitions. But the gold standard only contains 359 definitions, so I am expecting 66 more definitions in the goldstandard. 
Also: Of these definitions 217 have a field like `"W": [{"Q7913892": "Van der Waerden number"}]` which is a wikidata link (the `Q7913892` part) but the paper states that there are only 174 of those, this lead me to believe that there was something wrong with the gold standard.

**Comment by physikerwelt** [comment]
@leokraemer look here
https://github.com/TU-Berlin/mathosphere/blob/40651e80b1679fd788b42e4f0f5dcf0786fbf370/mathosphere-core/src/main/java/com/formulasearchengine/mathosphere/mlp/FlinkMlpRelationFinder.java#L83-L168
how the evaluation works. If you have suggestions on improving it this more than welcome.
Especially
https://github.com/TU-Berlin/mathosphere/blob/40651e80b1679fd788b42e4f0f5dcf0786fbf370/mathosphere-core/src/main/java/com/formulasearchengine/mathosphere/mlp/FlinkMlpRelationFinder.java#L116-L124
defines how the fp, fn, and tp values are calulated.

**Comment by physikerwelt** [comment]
Please also have a look at #105
However, there are still problems with that PR. Can you add the missing files and try to make the tests work on your machine?

**Comment by leokraemer** [comment]
Finally obtained a usable result using #105:
Threshold 0.8 has to be used and getNamespaceData(...) and selfMerge(...) must be deactivated.

```
Overall identifier evaluation
fp:58
fn:16
tp:294
Overall definition evaluation
fp=339; fn=222; tp=88
```

Still need to investigate where the 2 new fp come from though.

**Comment by leokraemer** [comment]
Also I can explain why the number of "false negatives" in the paper is completely unexplainable, it should read "false positives". About the Wikidata-links I still have no clue.

**Comment by leokraemer** [comment]
[Definiens extraction.txt](https://github.com/TU-Berlin/mathosphere/files/533386/Definiens.extraction.txt)
For future reference.

**Comment by leokraemer** [comment]
Overall identifier evaluation
fp:57
fn:16
tp:294
Overall definition evaluation
fp=337; fn=222; tp=88

I think reverting the mathqueryenerator 909011d did the trick.
with "-t", "0.8"
