### ISSUE TITLE
Make MathMLQueryGenerator a Git submodule?

### ISSUE THREAD

**Issue by jimmyli97** [TU-Berlin/mathosphere#43]
I noticed in the maven pom that mathmlquerygenerator is included as a local dependency - it doesn't use v0.0.2 which is on the maven central repository, rather it uses v0.0.3-SNAPSHOT. So anyone who wants to build this has to clone the current mathmlquerygenerator repo and build that as well, which I think is confusing.

I think we should make MathMLQueryGenerator into a submodule to make this simpler to build - is this ok?

**Comment by physikerwelt** [comment]
OK. We can drop the module in the future, when MathML query generator does
not change so frequently anymore.

**Comment by jimmyli97** [comment]
This was already a submodule - my mistake, I didn't see the lib folder
