### ISSUE TITLE
Make referenced XMLHelper consistent

### ISSUE THREAD

**Issue by jimmyli97** [TU-Berlin/mathosphere#53]
Currently basex, mathosphere-core, and mathmlquerygenerator all use their own copy of XMLHelper

XMLHelper should probably be placed somewhere that can be accessed by all three projects, instead of having three copies of XMLHelper, which makes things confusing

**Comment by physikerwelt** [comment]
XMLHelper can become part of MathMLQuery Generator but not the other way round. Making MathMLQuery generator depend on Mathosphere sounds not reasonable
