### ISSUE TITLE
ClientTest unit tests are failing

### ISSUE THREAD

**Issue by jimmyli97** [TU-Berlin/mathosphere#54]
They fail due to a "Connection refused" XQException. I think it's an inability to connect to the BaseX Server.

It appears to be some sort of problem with how XQConnection works - ServerTest runs fine, but ServerTest uses a ClientSession object to connect rather than a XQConnection.

Should we switch over to using a ClientSession with Query objects? Or is there a way to fix XQConnection?

**Comment by physikerwelt** [comment]
Do they fail locally for you or for the travis CI server. I don't remember failing tests when I executed it locally.

**Comment by jimmyli97** [comment]
They fail locally for me. I wrote a unit test for Server that uses the same XQConnection method and it runs fine, so I don't know what's wrong with the Client unit tests. I'll try to fix those today

**Comment by physikerwelt** [comment]
see

**Comment by physikerwelt** [comment]
ok sorry that's another bug
