### ISSUE TITLE
Refactor Results class

### ISSUE THREAD

**Issue by jimmyli97** [TU-Berlin/mathosphere#57]
This should be replaced with something such as a [DocumentBuilder](http://docs.oracle.com/javase/7/docs/api/javax/xml/parsers/DocumentBuilder.html). 

Currently the method of writing XML documents has polynomial time complexity - for every query there are x results, for every result there are x hits, for every hit there are x formulae. So to convert the document to a string will take O(n^4), which shouldn't be necessary. 

Building the XML document using a DocumentBuilder will reduce the write time to O(n), since the entire document can be written as a stream to a file. 

Should I do this now or later?

**Comment by physikerwelt** [comment]
I think this has low priority. However, changing that should not take to long. Please test the impact in seconds by perfroming the evaluation described at https://github.com/TU-Berlin/mathosphere/tree/master/basex "Steps performed for the submission"
I bet that the performance increase is less than 1% or 5 seconds.

**Comment by jimmyli97** [comment]
The other problem with nested classes is that it's impossible to do this:
```
currentResult.addHit(new Results.Run.Result.Hit(id, filename, score, rank ).addFormula(id, queryID, xref, score));
```
because inner classes are not static.

This means instantiating a new Results(), a new Run(), and a new Result() in order to instantiate a new Hit().

**Comment by jimmyli97** [comment]
I suppose a third solution would be to unnest all 4 classes
