### ISSUE TITLE
Make rest interface throw HTTP error codes

### ISSUE THREAD

**Issue by jimmyli97** [TU-Berlin/mathosphere#69]
Instead of returning errors in the response field, MathRequests should throw error codes if the query does not succeed. this is standard rest interface design I think

**Comment by physikerwelt** [comment]
this might make progressing the results harder

**Comment by jimmyli97** [comment]
what do you mean by this?

**Comment by physikerwelt** [comment]
Some http apis treat responses with a http status code > 400 different from an return code <400 thus the front end programmer would have to handle to types of responses

**Comment by jimmyli97** [comment]
Ok, I'll avoid doing this then. I'll keep returning errors in the response field
