### ISSUE TITLE
Enable option -T

### ISSUE THREAD

**Issue by physikerwelt** [TU-Berlin/mathosphere#83]
Make the test at
https://github.com/TU-Berlin/mathosphere/blob/master/mathosphere-core/src/test/java/com/formulasearchengine/mathosphere/mlp/cli/CliParamsTest.java#L22
work

**Comment by alexeygrigorev** [comment]
it wasn't possible to use `-T` because it conflicts with the `-t` param for setting the threshold

**Comment by physikerwelt** [comment]
This does not work yet as expected.
See the extended test in
16d4186a1d4c5ba59fb39e154dca3ca6ac00c76f
